# 브랜치 이름 형식 설정
# 'short': issue-이슈번호
# 'full': issue-이슈번호-이슈제목
# 'tiny': i이슈번호
branchName: 'short' # 요청하신 'short'로 설정

# Pull Request가 병합될 때 연결된 이슈를 자동으로 닫을지 여부
autoCloseIssue: true

# 브랜치 생성 트리거 모드 설정 (이전 답변에서 추가했던 내용)
# 'immediate': 이슈가 생성되거나 라벨이 붙는 즉시 브랜치 생성
# 'auto': 이슈에 담당자가 할당될 때 브랜치 생성 (기본값)
# 'chatops': 이슈 댓글에 '/cib' 명령어를 입력할 때 브랜치 생성
mode: 'immediate' # 이슈 생성/라벨링 즉시 브랜치 생성하도록 설정

# 라벨에 따른 브랜치 prefix 설정
# 이 부분이 'branches:' 대신 'labels:'로 변경되어야 합니다.
labels:
  - label: docs
    prefix: docs/
  - label: hotfix
    prefix: hotfix/
  - label: refactor
    prefix: refactor/
  - label: env
    prefix: chore/
  - label: release
    prefix: release/
  - label: test
    prefix: test/
  - label: bug
    prefix: fix/
  - label: question
    skip: true # 'question' 라벨일 경우 브랜치 생성 건너뛰기
  - label: '*' # 위 라벨 중 일치하는 것이 없을 경우, 기본값으로 'feature/' prefix 사용
    prefix: feature/

# 브랜치 생성 후 이슈에 남길 댓글 메시지 형식
commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'

# PR 생성 시 이슈의 속성을 PR로 복사할지 여부
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
