branchName: 'short' # 이슈 번호 기반 (예: issue-123)

# 라벨에 따른 prefix 설정 예시
labels:
  - label: 'feature'
    prefix: 'feature/'
  - label: 'bug'
    prefix: 'bugfix/'
  - label: '*' # 모든 라벨에 적용되는 기본값
    prefix: 'task/'

autoCloseIssue: true # 브랜지가 병합되면 이슈 자동 닫힘
commentMessage: 'Branch `${branchName}` created for issue: `${issue.title}`'
