# .github/workflows/issue-automation.yml
name: Issue → Project + Branch Automation

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues:   write

jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - name: Create branch from issue
        uses: robvanderleek/create-issue-branch@v2   # ← @v2 로 변경
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/issue-branch.yml      # @v2는 이 입력을 받음
